Repository chetannihith/Cpp-hacktoberfest25, pull requests merged in 2024-10, with the labels that each got.

#29 Added an interactive tic-tac-toe Game using C++
  Tic-Tac-Toe Game/game.cpp
  Tic-Tac-Toe Game/game.exe
Labels: hacktoberfest-accepted

#30 i have updated the code into new one
  Multiple Inheritance/build/Debug/marks_calculator_correct.o
  Multiple Inheritance/build/Debug/outDebug.exe
  Multiple Inheritance/marks_calculator.exe
  Multiple Inheritance/marks_calculator_correct.cpp
  Multiple Inheritance/marks_calculator_correct.exe
Labels: hacktoberfest-accepted

#31 Add new cpp program for tower of hanoi
  tower_of_hanoi/towerOfHanoi.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#34 code to some good problem of backtracking
  backtracking/k_kinights.cpp
  backtracking/k_kinights.exe
  backtracking/knights_tour.cpp
  backtracking/knights_tour.exe
  backtracking/permutation.cpp
  backtracking/permutation.exe
  backtracking/ratinamaize.cpp
  backtracking/ratinamaize.exe
Labels: hacktoberfest-accepted, hacktoberfest2024

#38 Frequency_Count
  Frequency_Count
Labels: hacktoberfest-accepted
